import FirebaseClient from "./firebaseClient.js";

/**
 * saveReport.js — Cloud Sync Bridge
 * ============================================================
 * Provides a high-level function to synchronize local test 
 * reports and healing events to Firebase Realtime Database.
 * ============================================================
 */

/**
 * Syncs a full test report to Firebase.
 * Handles both the run summary (history) and individual heal events.
 * 
 * @param {Object} report - The report object generated by writeReport
 * @returns {Promise<string|null>} The Firebase Run ID if successful
 */
export async function syncReportToFirebase(report) {
  if (!report) return null;

  console.log(`  [Firebase] Syncing results for: ${report.testFile}...`);

  try {
    // 1. Save the Run Summary to 'history'
    const runId = await FirebaseClient.saveRunHistory({
      testFile: report.testFile,
      timestamp: report.timestamp,
      summary: report.summary,
      status: report.summary.failed > 0 ? "failed" : "passed",
      stabilityScore: report.summary.stabilityScore
    });

    // 2. If there were heals, save each one to 'heals' linked to this run
    if (report.healDetails && report.healDetails.length > 0) {
      const healPromises = report.healDetails.map(heal => 
        FirebaseClient.saveHeal({
          ...heal,
          runId, // Link heal to this specific execution
          timestamp: report.timestamp,
          testFile: report.testFile
        })
      );
      
      await Promise.all(healPromises);
      console.log(`  [Firebase] Successfully synced ${report.healDetails.length} heal events.`);
    }

    console.log(`  [Firebase] Cloud sync complete (Run ID: ${runId})`);
    return runId;

  } catch (err) {
    console.warn(`  ⚠️  [Firebase] Sync failed: ${err.message}`);
    return null;
  }
}

export default syncReportToFirebase;
